### ISSUE TITLE
"qstat -q" only shows own jobs, not a general overview of queues/running jobs

### ISSUE THREAD

**Issue by boegel** [hpcugent/slurm-torque-wrappers#11]
@itkovian Can we do something about this, is there a Slurm command equivalent to what `qstat -q` does in Torque?

**Comment by stdweird** [comment]
why would we give users global state of queues? i considered it a bug in torque that you could get info about other jobs this way...

**Comment by boegel** [comment]
People find this useful to figure out which cluster is busier than others.

If we decide not to give the global overview on our Slurm clusters via `qstat -q`, we should let the `qstat` Slurm wrapper clearly mention that `qstat -q` does not give a global overview of jobs on the cluster, to avoid confusion...

I don't see anything really wrong with only giving a total count of queues vs running (even though it's pretty much meaningless since it doesn't say anything about requested resources).

**Comment by stdweird** [comment]
and what's wrong with pbsmon or the webpage?

**Comment by stdweird** [comment]
"People find this useful to figure out which cluster is busier than others.", what does the queue info add to this?

**Comment by boegel** [comment]
@stdweird A cluster that has 5 job waiting in the queue is significantly less "busy" in some sense than a cluster that has 10k jobs waiting in the queue.

This is not my view, but it's how I understand that users reason when picking a cluster currently.

Again, if we opt for not exposing this information to users anymore, fine, but then we should make that clear and not leave them guessing. Several people have brought this up.

**Comment by itkovian** [comment]
I do not think we should "fix" this. `squeue` only provides info on the own jobs, and I really want to keep it that way. We're not going to go the dshowq route again.

**Comment by boegel** [comment]
I'm fine with not fixing this in the sense that people get a general overview rather than only seeing counts for only own jobs with `qstat -q`, but we should make it crystal clear that only own jobs are shown with the `qstat` wrapper, by just making the wrapper print a short & clear message.

I can look into this, re-opening so I won't forget.

**Comment by alvarosimon** [comment]
an user has asked about this feature just to know how many jobs are still queued and how many are running

**Comment by hajgato** [comment]
fixed in #26
