### ISSUE TITLE
qsub wrapper should produce a clear error when job is submitted to a specific queue

### ISSUE THREAD

**Issue by boegel** [hpcugent/slurm-torque-wrappers#17]
Currently when users have `#PBS -q short` (or similar) in their job script and submit it using the `qsub` wrapper, it results in a cryptic error message like:

```
sbatch: error: invalid partition specified: default
sbatch: error: Batch job submission failed: Invalid partition name specified
```

Removing the `-q` spec fixes the problem. It occurs because there are no queues defined in the Slurm configuration like we had for Torque.

The queues have been useless in Torque for quite some time, so there's no point in defining them in Slurm, but a more meaningful error message that explains the problem (and suggests a fix) should be produced...

@itkovian Thoughts on this?

**Comment by stdweird** [comment]
map it for the old queue names to either something relevant in slurm or to nothing.
if there is not mapping, maybe a gentle waring that -q is not useful anymore 9but make sure it doesn't become useful in the future)
only if one selects a queue name that was not known in torque, throw an error

**Comment by itkovian** [comment]
I do not see the need for the latter. We'd then have to have some config file with the torque queue names. Otherwise this piece of code becomes useless for other people (or they'd need to modify the source code to reflect their own ex-torque queues).
