### ISSUE TITLE
incorrect resource requests are silently ignored

### ISSUE THREAD

**Issue by boegel** [hpcugent/slurm-torque-wrappers#49]
Submitting this job script to `joltik`:

```bash
$ cat test_joltik.sh
#!/bin/bash
#PBS -l nodes=1,ppn=8,gpus=1

taskset -p $$
nvidia-smi
```

results in:

```
$ cat test_joltik.sh.o40004288
pid 181793's current affinity mask: 10000
No devices were found
```

So, only one single core was used, and no GPUs were available.

The job script is wrong (it should use `nodes=1:ppn=8:gpus=1` (`:` rather than `,`), but it is accepted anyway, and the incorrectly specified resource requests are silently ignored.

**Comment by stdweird** [comment]
only the `,ppn=8` is wrong, `,gpus=1` is supported
not sure how we can fix the resources issue: we can't query the master to see what resources are supported. also, what does this do on torque (i mean the `,ppn=8` part)?

the gpu related issue is that we do not seem to handle the gpu statements in the PBS directives, so that is clearly wrong. we will not adapt the slurm pbs handler for this obviously.

**Comment by stdweird** [comment]
i have some idea how to solve this, but not that trivial. we will need to parse the resource PBS directives, which we have always delegated to the slurm plugin. it's not that complicated, but it's very close to getting rid of all PBS directive handling by slurm.

**Comment by boegel** [comment]
This sounds like an issue that would be a lot easier to handle in `jobcli` (which is not done yet, I'm well aware of that).

The main issue here is that using `,ppn=X` shouldn't be silently ignored.
Also, is using `,gpus=1` actually supported when used in a `#PBS` line in a job script? I don't think it is? See also #51.

Short term we can just detect `,ppn=` in a job script, and bail out with a decent error message (which mentions what do do instead). Likewise for `gpus=N` in a `#PBS` line. That should be pretty easy to implement, and is waaay easier than moving the actual parsing of the `#PBS` from Slurm into the wrapper (let's leave that effort to `jobcli`, where it's at least partially done already).

**Comment by stdweird** [comment]
what will `jobcli` do with `PBS` directives: convert in commandline args or SBATCH directives? it's pretty trivial to do this as well in teh current code, but i'm going to make a PR that only does this with `-l` (so i don't have to review the other existing code).

wrt `ppn`: should be easy to do for some fixed list (like `ppn`); but in general, i'm clueless how to do this. i can also throw a warning wrt "possible/likely typo"; or you want this to be fatal?

**Comment by boegel** [comment]
`jobcli` currently moves everything (`#PBS` lines + `qsub` command line option) to the job script (using `#SBATCH`), so everything is in one place

Using `,ppn=1` should be fatal imho, it doesn't make any sense, and we prevent job submission for other faulty requests too (like asking too many cores).

**Comment by stdweird** [comment]
have a look at
https://github.com/hpcugent/slurm-torque-wrappers/pull/52/commits/f1b9dadebb1480c2e0d55090f73cdbff02f81c91
