### ISSUE TITLE
"qsub -l nodes=1:ppn=1:gpus=1" results in "Requested node configuration is not available"

### ISSUE THREAD

**Issue by boegel** [hpcugent/slurm-torque-wrappers#50]
It seems like a minimum of `ppn=8` is required when requesting a GPU on `joltik`?

We should either remove that restriction, or make the error message clearer.

**Comment by stdweird** [comment]
this should be treated as a bug. either we find th emagic combination that does work (and some explanation wtf is wrong with mixing the defcpuspergpu with regular way of asking cores: i.e. file issue with slurm)
worst case, we remove the default in slurm.conf and do some default in the wrapper

**Comment by hajgato** [comment]
see: https://bugs.schedmd.com/show_bug.cgi?id=8199

**Comment by hajgato** [comment]
we have to define `--cpus-per-gpu=z`.

**Comment by stdweird** [comment]
so we have to set --cpus-per-gpu=0 and then the ppn value will work (as you can ask more cores then the default)?
or when gpus are used, people should only expect to work with cpus-per-gpu (we can have the ppn converted in cpus-per-gpu as close as possible)

**Comment by hajgato** [comment]
What they told, we have to calculate z based on ppn and gpus. But I will try `0`

**Comment by hajgato** [comment]
`Invalid numeric value "0" for --cpus-per-gpu`, so we have to set to a value based on `ppn`  and `gpus`

**Comment by stdweird** [comment]
my point is rather that his is a more principle issue: when using gpus, users should only expect cpus-per-gpu to be correct. gpus are the mai resources, cpus are secondary in that case (i'm fine with that)

**Comment by hajgato** [comment]
They say the behavior is by design. and if you want different than the default cpu per gpu, you must explicitly use `cpus-per-gpu`.

**Comment by stdweird** [comment]
the design is that cpus per tasks is not so relevant when gpus are being used

**Comment by hajgato** [comment]
Anyway, if we leave the defcpupergpu in the config file, we either have to inform the users in the wrapper that we have restrictions, or we have to educate them not to use `ppn`.

**Comment by stdweird** [comment]
or do best effort to convert ppn to match cpus-per-gpu as close as possibel

**Comment by hajgato** [comment]
indeed.

**Comment by boegel** [comment]
I have a strong preference for having a sensible default (but allow to override it if needed) rather than trying to educate users about either restrictions or (not) using `<whatever>` (since that's a battle we're doomed to lose)

**Comment by stdweird** [comment]
@hajgato the code now is fatal for `--cpus-per-gpu` without `--gpus` option (ie the `--gres=gpu` might not work). however, it also has `# apparently, only when --gpus is set (according to man page)`
so needs to be tested first it is a possible solution

**Comment by stdweird** [comment]
#53 derives a cpus-per-gpu from ppn, and possibly modifies ppn. there's a caveat due ot the way processing is done, i hope jobcli does proper conversion taking other setting in account (or has another approach to the issue)
