### ISSUE TITLE
filenames for job stdout/stderr do not match with those produced by Torque

### ISSUE THREAD

**Issue by boegel** [hpcugent/slurm-torque-wrappers#9]
```
$ cat t.sh
#!/bin/bash
echo $PWD

$ qsub --debug -d /scratch/gent/400/vsc40023/EasyBuild_regression_test_results t.sh
DEBUG: Generated command '/usr/bin/sbatch --chdir=/scratch/gent/400/vsc40023/EasyBuild_regression_test_results -J t.sh -e /kyukon/home/gent/400/vsc40023/%j.e%A --export=NONE --get-user-env=60L -o /kyukon/home/gent/400/vsc40023/%j.o%A'
DEBUG: Got output Submitted batch job 7344967 on cluster victini
7344967
```

results in:

```
$ ls -lrt *7344*
-rw-rw-r-- 1 vsc40023 vsc40023   0 Dec  5 12:04 7344967.e7344967
-rw-rw-r-- 1 vsc40023 vsc40023 108 Dec  5 12:04 7344967.o7344967
```

Should be `t.sh.o7344967` and `t.sh.e7344967`, since in Torque the script filename is used as job name if no job name is specified via `-N`.

`t.sh` is being used as job name though:

```
$ qstat
gligar04.gastly.os:
                                                                               Req'd  Req'd      Elap
Job id               Username Queue    Name                 SessID NDS   TSK   Memory Time Use S Time
-------------------- -------- -------- -------------------- ------ ----- ----- ------ -------- - --------
7344967              vsc40023 victini  t.sh                 --         1     1     -- 01:00:00 R 00:00:04
```

**Comment by boegel** [comment]
One more situation where the handling of `-o` and `-e` is different: if the location specified to `#PBS -o` is an existing directory, then the `qsub` wrapper isn't handling that correctly right now. Expected behavior (as observed with Torque) is that the output file is then placed *in* that directory (cfr. OTRS Ticket#1000031663).

**Comment by boegel** [comment]
Works as expected:

```
#!/bin/bash
#PBS -o test.out
#PBS -e test.err
echo $PBS_JOBID
echo "this is an error" >&2
```

Example usage:

```
$ qsub t.sh
...
$ ls
t.sh     test. err    test.out
$ cat test.out
7713501
$ cat test.err
this is an error
```


Does *not* work as expected (this is just one example):

```
#!/bin/bash
echo $PBS_JOBID
echo "this is an error" >&2
```

Example usage:

```
$ qsub t.sh
$ ls
7713503.e7713503  7713503.o7713503   t.sh
```

Output files should be `t.sh.e*` and `t.sh.o*`.

Same problem when job name is specified using `#PBS -N test` in job script,
so this looks like a simple mixup of job name & job ID in the `qsub` wrapper?

It does work fine when using `qsub -N test t.sh` though (without having `#PBS -N test` in the job script):

```
$ qsub -N test t.sh
7713505

$ ls *7713505*
test.e7713505  test.o7713505
$ cat test.e7713505
this is an error
$ cat test.o7713505
7713505
```

This suggests that the problem is (partially) in the handling of `#PBS -N`, which is done somewhere in the Slurm code (not in the `qsub` wrapper) afaik...

**Comment by boegel** [comment]
@hajgato Was this fully fixed with #13?

**Comment by hajgato** [comment]
@boegel Yes.

**Comment by boegel** [comment]
@hajgato Another related problem was reported: if a *directory* is passed to the `-o` and/or `-e` options for `qsub`, no output files are created at all...

Even worse, the job doesn't even execute, and there's no way of telling what is wrong, no sign of any errors...


Test case:
```
$ cat t.sh
#!/bin/bash
echo $PBS_JOBID
echo "this is an error" >&2

$ qsub t.sh -o $HOME/outputs/
7876192

$ qstat
Job id              Name             Username        Time Use    S Queue
------------------- ---------------- --------------- --------    - ---------------
7876192             t.sh             vsc40023        00:00:04    C victini

$ ls -lrt *7876192* outputs/*7876192*
ls: cannot access *7876192*: No such file or directory
ls: cannot access outputs/*7876192*: No such file or directory
```

It does work properly a file path is specified to `-o`:

```
$ qsub t.sh -o $HOME/outputs/out.txt
7876193

$ ls -lrt *7876193* outputs/out.txt
-rw-rw-r-- 1 vsc40023 vsc40023  8 Mar 21 14:21 outputs/out.txt
-rw-rw-r-- 1 vsc40023 vsc40023 17 Mar 21 14:21 t.sh.e7876193
$ cat outputs/out.txt
7876193

**Comment by hajgato** [comment]
PR 16 solved this problem.
